import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author victor.gsmiranda
 */
public class alterarAlunos extends javax.swing.JFrame {

    /**
     * Creates new form alterarAlunos
     */
    public alterarAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        titleVarejo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        lblNomeAlterarAluno = new javax.swing.JLabel();
        lblCpfAlterarAluno = new javax.swing.JLabel();
        txtCpfAluno = new javax.swing.JTextField();
        lblTelefoneAlterarAluno = new javax.swing.JLabel();
        txtTelefonealuno = new javax.swing.JTextField();
        btnSalvarAlteracoes = new javax.swing.JButton();
        lblCursoAlterarAluno = new javax.swing.JLabel();
        txtCursoAluno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Alunos");
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        titleVarejo.setText("VarejoPro");
        titleVarejo.setMaximumSize(new java.awt.Dimension(60, 16));
        jPanel5.add(titleVarejo);
        titleVarejo.setBounds(190, 50, 60, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo varejo 2.png"))); // NOI18N
        jPanel5.add(jLabel2);
        jLabel2.setBounds(130, 40, 53, 36);

        txtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoActionPerformed(evt);
            }
        });
        jPanel5.add(txtNomeAluno);
        txtNomeAluno.setBounds(110, 130, 230, 30);

        lblNomeAlterarAluno.setText("Nome:");
        jPanel5.add(lblNomeAlterarAluno);
        lblNomeAlterarAluno.setBounds(40, 130, 50, 20);

        lblCpfAlterarAluno.setText("CPF:");
        jPanel5.add(lblCpfAlterarAluno);
        lblCpfAlterarAluno.setBounds(40, 200, 60, 16);

        txtCpfAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfAlunoActionPerformed(evt);
            }
        });
        jPanel5.add(txtCpfAluno);
        txtCpfAluno.setBounds(110, 190, 230, 30);

        lblTelefoneAlterarAluno.setText("Telefone:");
        jPanel5.add(lblTelefoneAlterarAluno);
        lblTelefoneAlterarAluno.setBounds(40, 250, 70, 20);

        txtTelefonealuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonealunoActionPerformed(evt);
            }
        });
        jPanel5.add(txtTelefonealuno);
        txtTelefonealuno.setBounds(110, 240, 230, 30);

        btnSalvarAlteracoes.setBackground(new java.awt.Color(0, 153, 0));
        btnSalvarAlteracoes.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarAlteracoes.setText("Salvar Alterações");
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalvarAlteracoes);
        btnSalvarAlteracoes.setBounds(90, 370, 210, 40);

        lblCursoAlterarAluno.setText("Curso:");
        jPanel5.add(lblCursoAlterarAluno);
        lblCursoAlterarAluno.setBounds(40, 300, 70, 20);

        txtCursoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoAlunoActionPerformed(evt);
            }
        });
        jPanel5.add(txtCursoAluno);
        txtCursoAluno.setBounds(110, 290, 230, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(60, 30, 369, 470);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 480, 570);

        setSize(new java.awt.Dimension(486, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfAlunoActionPerformed

    private void txtTelefonealunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonealunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonealunoActionPerformed

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        // 1- pegar os dados dos campos
        String nome, cpf, telefone, curso;
        nome = txtNomeAluno.getText();
        cpf = txtCpfAluno.getText();
        telefone = txtTelefonealuno.getText();
        curso = txtCursoAluno.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conectar = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/VarejoPro","root","Sarti007@");
            PreparedStatement st = conectar.prepareStatement("UPDATE aluno SET cpf = ?, telefone = ?, curso =?  WHERE nome =?");
            st.setString(1, cpf);
            st.setString(2, telefone);
            st.setString(3, curso);
            st.setString(4, nome);
            //falta o comando qyue altera aqui
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Dados alterado com sucesso");
            dispose(); //fevha a tela
        } catch (ClassNotFoundException | java.sql.SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Erro:" + ex.getMessage());
        }

    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void txtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoActionPerformed

    private void txtCursoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alterarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alterarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alterarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alterarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alterarAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCpfAlterarAluno;
    private javax.swing.JLabel lblCursoAlterarAluno;
    private javax.swing.JLabel lblNomeAlterarAluno;
    private javax.swing.JLabel lblTelefoneAlterarAluno;
    private javax.swing.JLabel titleVarejo;
    private javax.swing.JTextField txtCpfAluno;
    private javax.swing.JTextField txtCursoAluno;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtTelefonealuno;
    // End of variables declaration//GEN-END:variables
}
