
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author victor.gsmiranda
 */
public class AlterarCursos extends javax.swing.JFrame {

    /**
     * Creates new form AlterarCursos
     */
    public AlterarCursos() {
        initComponents();

    }

    public AlterarCursos(String n, String dr, String des) {
        initComponents();
        txtNome.setText(n);
        txtDuracao.setText(dr);
        txtDescricao.setText(des);
        txtNome.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        titleVarejo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDuracaoAlterarCurso = new javax.swing.JLabel();
        txtDuracao = new javax.swing.JTextField();
        lblDescricaoCurso = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnSalvarAlteracoes = new javax.swing.JButton();
        lblNomeAlterarCurso = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Cursos");
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        titleVarejo.setText("VarejoPro");
        titleVarejo.setMaximumSize(new java.awt.Dimension(60, 16));
        jPanel5.add(titleVarejo);
        titleVarejo.setBounds(190, 50, 60, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo varejo 2.png"))); // NOI18N
        jPanel5.add(jLabel2);
        jLabel2.setBounds(130, 40, 53, 36);

        lblDuracaoAlterarCurso.setText("Duração:");
        jPanel5.add(lblDuracaoAlterarCurso);
        lblDuracaoAlterarCurso.setBounds(50, 180, 60, 16);

        txtDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracaoActionPerformed(evt);
            }
        });
        jPanel5.add(txtDuracao);
        txtDuracao.setBounds(110, 170, 230, 30);

        lblDescricaoCurso.setText("Descrição:");
        jPanel5.add(lblDescricaoCurso);
        lblDescricaoCurso.setBounds(50, 240, 70, 20);

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        jPanel5.add(txtDescricao);
        txtDescricao.setBounds(110, 230, 230, 30);

        btnSalvarAlteracoes.setBackground(new java.awt.Color(51, 153, 0));
        btnSalvarAlteracoes.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarAlteracoes.setText("Salvar Alterações");
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalvarAlteracoes);
        btnSalvarAlteracoes.setBounds(100, 310, 210, 40);

        lblNomeAlterarCurso.setText("Nome:");
        jPanel5.add(lblNomeAlterarCurso);
        lblNomeAlterarCurso.setBounds(50, 110, 50, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel5.add(txtNome);
        txtNome.setBounds(110, 110, 230, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(50, 20, 369, 400);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 500);

        setSize(new java.awt.Dimension(486, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracaoActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        // 1- pegar os dados dos campos
        String n, dr, des;
        n = txtNome.getText();
        dr = txtDuracao.getText();
        des = txtDescricao.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/VarejoPro","root","Sarti007@");
            PreparedStatement st = conectar.prepareStatement("UPDATE curso SET duracao = ?, descricao = ?  WHERE nome =?");
            st.setString(1, dr);
            st.setString(2, des);
            st.setString(3, n);
            //falta o comando qyue altera aqui
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Dados alterado com sucesso");
            dispose(); //fevha a tela
        } catch (ClassNotFoundException | java.sql.SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Erro:" + ex.getMessage());
        }
    
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblDescricaoCurso;
    private javax.swing.JLabel lblDuracaoAlterarCurso;
    private javax.swing.JLabel lblNomeAlterarCurso;
    private javax.swing.JLabel titleVarejo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
