
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author victor.gsmiranda
 */
public class CadastrarAlunos extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarAlunos
     */
    public CadastrarAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        titleVarejo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbnNomeAluno = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        lbnCpfAluno = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        txtTelefoneAluno = new javax.swing.JTextField();
        txtCursoAluno = new javax.swing.JTextField();
        txtCpfAluno = new javax.swing.JTextField();
        lbnTelefoneAluno = new javax.swing.JLabel();
        lbnCursoAluno = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Alunos");
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        titleVarejo.setText("VarejoPro");
        titleVarejo.setMaximumSize(new java.awt.Dimension(60, 16));
        jPanel2.add(titleVarejo);
        titleVarejo.setBounds(167, 52, 60, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo varejo 2.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(108, 40, 53, 36);

        lbnNomeAluno.setText("Nome:");
        jPanel2.add(lbnNomeAluno);
        lbnNomeAluno.setBounds(40, 140, 90, 40);

        btnSalvar.setBackground(new java.awt.Color(51, 102, 0));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setMnemonic('e');
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);
        btnSalvar.setBounds(80, 410, 210, 50);

        lbnCpfAluno.setText("CPF:");
        jPanel2.add(lbnCpfAluno);
        lbnCpfAluno.setBounds(40, 190, 60, 40);

        txtNomeAluno.setToolTipText("");
        txtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNomeAluno);
        txtNomeAluno.setBounds(110, 140, 190, 40);

        txtTelefoneAluno.setToolTipText("");
        txtTelefoneAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneAlunoActionPerformed(evt);
            }
        });
        jPanel2.add(txtTelefoneAluno);
        txtTelefoneAluno.setBounds(110, 240, 190, 40);

        txtCursoAluno.setToolTipText("");
        txtCursoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoAlunoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCursoAluno);
        txtCursoAluno.setBounds(110, 290, 190, 40);

        txtCpfAluno.setToolTipText("");
        txtCpfAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfAlunoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCpfAluno);
        txtCpfAluno.setBounds(110, 190, 190, 40);

        lbnTelefoneAluno.setText("Telefone:");
        jPanel2.add(lbnTelefoneAluno);
        lbnTelefoneAluno.setBounds(40, 240, 80, 30);

        lbnCursoAluno.setText("Curso:");
        jPanel2.add(lbnCursoAluno);
        lbnCursoAluno.setBounds(40, 290, 60, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 30, 369, 524);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 600);

        setSize(new java.awt.Dimension(505, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add U your handling code here:
        String nome, cpf, telefone, curso;
        nome = txtNomeAluno.getText();
        cpf = txtCpfAluno.getText();
        telefone = txtTelefoneAluno.getText();
        curso = txtCursoAluno.getText();

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/VarejoPro","root","Sarti007@");
           PreparedStatement st = (PreparedStatement) conectar.prepareStatement("INSERT INTO aluno VALUES(?,?,?,?)");
            st.setString(1,nome);
            st.setString(2,cpf);
            st.setString(3,telefone);
            st.setString(4, curso);
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso");
            //5- Limpar os campos
            txtNomeAluno.setText("");
            txtCpfAluno.setText("");
            txtTelefoneAluno.setText("");
            txtCursoAluno.setText("");
            txtNomeAluno.requestFocus(); // Posiciona o cursor no campo usuario

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro encontrado, entre em contato com suporte e informe o erro:" + ex.getMessage());
        } catch (java.sql.SQLException ex) {
            String erro = ex.getMessage();
            if(erro.contains("Duplicate entry")){
                JOptionPane.showMessageDialog(null, "Aluno já cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro encontrado, entre em contato com suporte e informe o erro:" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoActionPerformed

    private void txtTelefoneAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneAlunoActionPerformed

    private void txtCursoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoAlunoActionPerformed

    private void txtCpfAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbnCpfAluno;
    private javax.swing.JLabel lbnCursoAluno;
    private javax.swing.JLabel lbnNomeAluno;
    private javax.swing.JLabel lbnTelefoneAluno;
    private javax.swing.JLabel titleVarejo;
    private javax.swing.JTextField txtCpfAluno;
    private javax.swing.JTextField txtCursoAluno;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtTelefoneAluno;
    // End of variables declaration//GEN-END:variables
}
