
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author victor.gsmiranda
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCursos = new javax.swing.JMenu();
        itmCadastrarCursos = new javax.swing.JMenuItem();
        itmAlterarCursos = new javax.swing.JMenuItem();
        itmListarCursos = new javax.swing.JMenuItem();
        itmExcluirCursos = new javax.swing.JMenuItem();
        MenuCadastro = new javax.swing.JMenu();
        itmCadastrarUsuario = new javax.swing.JMenuItem();
        itmAlterarUsuario = new javax.swing.JMenuItem();
        itmListarUsuario = new javax.swing.JMenuItem();
        itmExcluirUsuario = new javax.swing.JMenuItem();
        menuAlunos = new javax.swing.JMenu();
        itmCadastrarAlunos = new javax.swing.JMenuItem();
        itmAlterarAlunos = new javax.swing.JMenuItem();
        itmListarAlunos = new javax.swing.JMenuItem();
        itmExcluirAlunos = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        itmTrocarusuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo varejo 2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 220, 60, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 580);

        jMenuBar1.setToolTipText("");
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuCursos.setText("Cursos");

        itmCadastrarCursos.setText("Cadastrar");
        itmCadastrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarCursosActionPerformed(evt);
            }
        });
        MenuCursos.add(itmCadastrarCursos);

        itmAlterarCursos.setText("Alterar ");
        itmAlterarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarCursosActionPerformed(evt);
            }
        });
        MenuCursos.add(itmAlterarCursos);

        itmListarCursos.setText("Listar");
        itmListarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarCursosActionPerformed(evt);
            }
        });
        MenuCursos.add(itmListarCursos);

        itmExcluirCursos.setText("Excluir");
        itmExcluirCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirCursosActionPerformed(evt);
            }
        });
        MenuCursos.add(itmExcluirCursos);

        jMenuBar1.add(MenuCursos);

        MenuCadastro.setText("Usuários");

        itmCadastrarUsuario.setText("Cadastrar");
        itmCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarUsuarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(itmCadastrarUsuario);

        itmAlterarUsuario.setText("Alterar");
        itmAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarUsuarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(itmAlterarUsuario);

        itmListarUsuario.setText("Listar");
        itmListarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarUsuarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(itmListarUsuario);

        itmExcluirUsuario.setText("Excluir");
        itmExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirUsuarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(itmExcluirUsuario);

        jMenuBar1.add(MenuCadastro);

        menuAlunos.setText("Alunos");

        itmCadastrarAlunos.setText("Cadastrar");
        itmCadastrarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarAlunosActionPerformed(evt);
            }
        });
        menuAlunos.add(itmCadastrarAlunos);

        itmAlterarAlunos.setText("Alterar");
        itmAlterarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarAlunosActionPerformed(evt);
            }
        });
        menuAlunos.add(itmAlterarAlunos);

        itmListarAlunos.setText("Listar");
        itmListarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarAlunosActionPerformed(evt);
            }
        });
        menuAlunos.add(itmListarAlunos);

        itmExcluirAlunos.setText("Excluir");
        itmExcluirAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirAlunosActionPerformed(evt);
            }
        });
        menuAlunos.add(itmExcluirAlunos);

        jMenuBar1.add(menuAlunos);

        MenuSair.setText("Sair");

        itmTrocarusuario.setText("Trocar usuário");
        itmTrocarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmTrocarusuarioActionPerformed(evt);
            }
        });
        MenuSair.add(itmTrocarusuario);

        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(916, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarUsuarioActionPerformed
        new ListarUsuarios().setVisible(true);
    }//GEN-LAST:event_itmListarUsuarioActionPerformed

    private void itmCadastrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarCursosActionPerformed
       new CadastrarCursos().setVisible(true);
    }//GEN-LAST:event_itmCadastrarCursosActionPerformed

    private void itmAlterarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarCursosActionPerformed

        
          // obter o nome e senha do usuario
        String u;
        u = JOptionPane.showInputDialog("Nome do Curso");
         try {
            //conectar ao Bamco de dados "empresa"
          Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/VarejoPro","root","Sarti007@");
           // 3- enviar os dados para a tabela BD
        PreparedStatement st = conectar.prepareStatement("SELECT * FROM curso WHERE nome =?"); 
        st.setString(1, u);
             ResultSet nome = st.executeQuery();
             //4- Verificar se encontrou o usuario na tabela bd
             if(nome.next()){//se encontrou o usuario 
                 //5- enviar os dados do usuarios para a tela AlterarUsuarios
                 String n,dr,des;
                 n = nome.getString("nome"); 
                 dr = nome.getString("duracao");
                 des = nome.getString("descricao");
                new AlterarCursos(n, dr, des).setVisible(true);
                 
             } else{ //se nao encontrou 
                 JOptionPane.showMessageDialog(null, "Curso não encontrado");
             }
             
         } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro encontrado, entre em contato com suporte e informe o erro:" + ex.getMessage());
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_itmAlterarCursosActionPerformed

    private void itmListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarCursosActionPerformed
        new ListarCursos().setVisible(true);
        
    }//GEN-LAST:event_itmListarCursosActionPerformed

    private void itmExcluirCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirCursosActionPerformed
        String i;
        i = JOptionPane.showInputDialog("Nome do Curso");

        try{
            //conectar ao banco de dados
            Connection conectar = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/VarejoPro","root","Sarti007@");
            PreparedStatement st = conectar.prepareStatement("DELETE FROM curso WHERE nome = ?");
            // excluir usuarios
            st.setString(1,i);
            int retorno = st.executeUpdate(); // executar deletes
            if (retorno ==1)
            JOptionPane.showMessageDialog(null, "Curso excluido com sucesso");
            else JOptionPane.showMessageDialog(null, "Curso não encontrado");

        } catch (SQLException ex){
            JOptionPane.showConfirmDialog(null, "Erro:" + ex.getMessage());

        }

    }//GEN-LAST:event_itmExcluirCursosActionPerformed

    private void itmCadastrarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarAlunosActionPerformed
        new CadastrarAlunos().setVisible(true);
    }//GEN-LAST:event_itmCadastrarAlunosActionPerformed

    private void itmAlterarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarAlunosActionPerformed
        new alterarAlunos().setVisible(true);
    }//GEN-LAST:event_itmAlterarAlunosActionPerformed

    private void itmExcluirAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirAlunosActionPerformed
      String i;
        i = JOptionPane.showInputDialog("Nome do Aluno");

        try{
            //conectar ao banco de dados
            Connection conectar = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/VarejoPro","root","Sarti007@");
            PreparedStatement st = conectar.prepareStatement("DELETE FROM aluno WHERE nome = ?");
            // excluir usuarios
            st.setString(1,i);
            int retorno = st.executeUpdate(); // executar deletes
            if (retorno ==1)
            JOptionPane.showMessageDialog(null, "Aluno excluido com sucesso");
            else JOptionPane.showMessageDialog(null, "Aluno não encontrado");

        } catch (SQLException ex){
            JOptionPane.showConfirmDialog(null, "Erro:" + ex.getMessage());

        }
    }//GEN-LAST:event_itmExcluirAlunosActionPerformed

    private void itmTrocarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmTrocarusuarioActionPerformed
       dispose();
       new login().setVisible(true);
    }//GEN-LAST:event_itmTrocarusuarioActionPerformed

    private void itmListarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarAlunosActionPerformed
        new ListarAlunos().setVisible(true);
    }//GEN-LAST:event_itmListarAlunosActionPerformed

    private void itmCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarUsuarioActionPerformed
        new CadastroUsuario().setVisible(true);
    }//GEN-LAST:event_itmCadastrarUsuarioActionPerformed

    private void itmAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarUsuarioActionPerformed
       new AlterarUsuarios().setVisible(true);
    }//GEN-LAST:event_itmAlterarUsuarioActionPerformed

    private void itmExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirUsuarioActionPerformed
       String i;
        i = JOptionPane.showInputDialog("Nome Do Usuaário");

        try{
            //conectar ao banco de dados
            Connection conectar = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/VarejoPro","root","Sarti007@");
            PreparedStatement st = conectar.prepareStatement("DELETE FROM usuarios WHERE email = ?");
            // excluir usuarios
            st.setString(1,i);
            int retorno = st.executeUpdate(); // executar deletes
            if (retorno ==1)
            JOptionPane.showMessageDialog(null, "Usuário excluido com sucesso");
            else JOptionPane.showMessageDialog(null, "Usuário não encontrado");

        } catch (SQLException ex){
            JOptionPane.showConfirmDialog(null, "Erro:" + ex.getMessage());

        }
    }//GEN-LAST:event_itmExcluirUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuCursos;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuItem itmAlterarAlunos;
    private javax.swing.JMenuItem itmAlterarCursos;
    private javax.swing.JMenuItem itmAlterarUsuario;
    private javax.swing.JMenuItem itmCadastrarAlunos;
    private javax.swing.JMenuItem itmCadastrarCursos;
    private javax.swing.JMenuItem itmCadastrarUsuario;
    private javax.swing.JMenuItem itmExcluirAlunos;
    private javax.swing.JMenuItem itmExcluirCursos;
    private javax.swing.JMenuItem itmExcluirUsuario;
    private javax.swing.JMenuItem itmListarAlunos;
    private javax.swing.JMenuItem itmListarCursos;
    private javax.swing.JMenuItem itmListarUsuario;
    private javax.swing.JMenuItem itmTrocarusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAlunos;
    // End of variables declaration//GEN-END:variables
}
